### ISSUE TITLE
The status of the individual channels don't update until restarting the app

### ISSUE THREAD

**Issue by bjarnemagnussen** [neogeno/shango-lightning-wallet#25]
- OS (Android/iOS)   LineageOS (no GApps)
- Version of OS  8.1.0
- Device Make and Model   Xiaomi Redmi Note 4
- Shango Version  1.0
- Device ID (Look in Settings-About Shango)  6944746084732e5a

The display of the status (showing "opening", "open", "active" or "closing") and display of local and remote amounts does only update once upon (re)starting the Shango app. Only when opening a channel is that channel immediately added to the list but the display of the status stays static as "opening". 
 
## Expected Behavior
Just like the aggregate display inside the black bar above the list of channels is updated, so should the list of the individual channels update the status and display of current amounts immediately.

## Current Behavior
The status and amounts in the list of the individual channels is static. Only updated upon (re)starting of Shango.

## Steps to Reproduce
1. Open a new channel / Send satoshis via some channel
2. The status / amount shown is not updated.
3. Restarting the Shango app updates the display in the list of channels to reflect on the current state.
4. But the display will again stay static and is only updated whenever Shango app is started.

**Comment by bjarnemagnussen** [comment]
By the way, when I close a channel even though the local amount shown is wrong it does actually close it using the correct current state and the right amount is returned. So it is only a display problem.

**Comment by neogeno** [comment]
Thank you, Shango l periodically poll sthe LND server right now every 30 seconds so if you make payments during that time your local balance will not update till the next scheduled polling. 

When you make a payment via Lightning, after the green confirm screen is shown, it will update the channel list as well. Unfortunately, I accidentally commented that post-confirm refresh line of code so it will be fixed in the next build.

**Comment by neogeno** [comment]
Fixed in upcoming Build 18
