### ISSUE TITLE
Error Processing QR

### ISSUE THREAD

**Issue by RhinoAK** [neogeno/shango-lightning-wallet#81]
Thank you for trying out Shango Beta.   

Please submit your issues with the following information

- OS (Android/iOS)   - **Android**
- Version of OS   - **9 build PPR1.180610.011**
- Device Make and Model   **Samsung S9**
- Shango Version  **0.5.0 beta**
- Device ID **c52d9c48dca6e2fd** 

## Steps to Reproduce

1. 1st generate the code using qrencode from steps found - Bonus guide: Shango Mobile Lightning Wallet - https://stadicus.github.io/RaspiBolt/raspibolt_68_shango.html .
2. After generating the code I open up Shango go into Wrentch > Connect to other LND Nodes > Scan QR
3. Scan the image, Shango detects the image but then I immediately get the error.

**Comment by neogeno** [comment]
Please try to scan this QR code for my demo self-hosted node to see if you can connect. If you can connect successfully, the problem is with your LND configuration / QR Code. 

Click View Instructions on the Connect screen to see more detailed setup guides.

![Screenshot 2019-06-30 03 43 19](https://user-images.githubusercontent.com/4373046/60388824-4e1b9a00-9ae9-11e9-93e7-a7e341926505.png)
